[book]
authors = ["Optimism Contributors"]
language = "en"
multilingual = false
src = "src"
title = "Optimism Monorepo Ops"

[output.html]
site-url = "/monorepo-ops/"
git-repository-url = "https://github.com/flexdeal-chain/fd-chain/tree/develop/ops/book"
edit-url-template = "https://github.com/flexdeal-chain/fd-chain/tree/develop/ops/book/{path}"
